## Домашнее задание №2
Даны одномерный массив A и число n. Вычислите массив B, в котором i-й элемент равен среднему значению элементов с i-го по (i+n-1)-й в массиве A.

In [1]:
import numpy as np

In [2]:
def moving_avg(a, n):
    '''Возвращает массив, в котором каждый элемент
    равен скользящему среднему значению элементов
    с i-го по (i+n-1)-й
        
    Parameters
    ----------
    a : numpy.array
        обрабатываемый массив
    n : int
        диапазон для среднего значения'''
    
    b = np.zeros(len(a))
    for i in range(len(a)):
        b[i] = np.mean(a[i:(i+n)])
    return b[:-n + 1]

In [3]:
# случайный массив из 10 чисел от 0 до 100
a = np.random.choice(100, 10)
a

array([28, 36, 85, 92, 96, 18, 87, 85, 29, 25])

In [4]:
n = 3  # скользящее по трём элементам
moving_avg(a, n)

array([49.66666667, 71.        , 91.        , 68.66666667, 67.        ,
       63.33333333, 67.        , 46.33333333])

In [5]:
n = 2  # скользящее по двум элементам
moving_avg(a, n)

array([32. , 60.5, 88.5, 94. , 57. , 52.5, 86. , 57. , 27. ])